from django.db import connection
import celery

# pylint: disable=W0223

class FaultTolerantTask(celery.Task):  # pragma: no cover
    """ Implements after return hook to close the invalid connection.
    This way, django is forced to serve a new connection for the next
    task.
    """
    abstract = True

    def after_return(self, *args, **kwargs):
        connection.close()
